# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Hack3',
                'doc_host': 'https://isc-ryoung.github.io',
                'git_url': 'https://github.com/isc-ryoung/Hack3',
                'lib_path': 'Hack3'},
  'syms': {'Hack3.core': {'Hack3.core.foo': ('core.html#foo', 'Hack3/core.py')}}}
