"""The main Remediator agent that orchestrates the resolution of IRIS instance problems using IrisDb and Customer agents."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_remediator.ipynb.

# %% auto #0
__all__ = ['ProblemType', 'Problem', 'Resolution', 'RemediatorAgent']

# %% ../nbs/01_remediator.ipynb #imports_main
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field
from enum import Enum
import json
from openai import OpenAI

# %% ../nbs/01_remediator.ipynb #problem_type
class ProblemType(Enum):
    """Types of problems that can occur in IRIS instance."""
    LICENSE = "license"
    CONFIGURATION = "configuration"
    OS_RESOURCE = "os_resource"
    UNKNOWN = "unknown"

# %% ../nbs/01_remediator.ipynb #problem_class
@dataclass
class Problem:
    """Structured representation of a problem detected in IRIS instance."""
    problem_type: str
    description: str
    severity: str  # 'critical', 'high', 'medium', 'low'
    log_entry: Optional[str] = None
    affected_component: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'problem_type': self.problem_type,
            'description': self.description,
            'severity': self.severity,
            'log_entry': self.log_entry,
            'affected_component': self.affected_component
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Problem':
        return cls(**data)

# %% ../nbs/01_remediator.ipynb #resolution_class
@dataclass
class Resolution:
    """Possible resolution for a problem."""
    action: str
    description: str
    requires_restart: bool = False
    parameters: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'action': self.action,
            'description': self.description,
            'requires_restart': self.requires_restart,
            'parameters': self.parameters
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Resolution':
        return cls(**data)

# %% ../nbs/01_remediator.ipynb #remediator_agent
try:
    from openai.agents import Agent
except ImportError:
    Agent = None

class RemediatorAgent:
    """Main Remediator agent using OpenAI SDK Agents framework."""
    
    def __init__(self, api_key: str, model: str = "gpt-4o"):
        """Initialize the Remediator Agent.
        
        Args:
            api_key: OpenAI API key
            model: Model to use for the agent
        """
        self.client = OpenAI(api_key=api_key)
        self.model = model
        self.history: List[Dict[str, Any]] = []
        
        if Agent:
            self.agent = Agent(
                name="Remediator",
                model=self.model,
                instructions="Resolve problems with InterSystems IRIS instance."
            )
        else:
            self.agent = None
    
    def log_step(self, step: str, data: Any) -> None:
        """Log a workflow step."""
        self.history.append({'step': step, 'data': data})
    
    async def remediate(self, prompt: str) -> str:
        """Main remediation workflow."""
        self.log_step('remediate_start', {'prompt': prompt})
        
        if not self.agent:
            return "OpenAI Agents SDK not available."
        
        try:
            response = await self.agent.run(prompt)
            report = str(response)
            self.log_step('remediate_complete', {'report': report})
            return report
        except Exception as e:
            error_msg = f"Error: {str(e)}"
            self.log_step('remediate_error', {'error': error_msg})
            return error_msg
